server:
  port: 8082
  servlet:
    context-path: /api
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30





spring:
  datasource:
    url: jdbc:mysql://47.111.161.18:3306/bgd?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: bgd@2019
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      initial-size: 5
      max-wait: 60000
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  redis:
    host: 47.111.161.18
    port: 6379


  #整合消息队列
  rabbitmq:
    host: 47.111.161.18
    port: 5672
    username: admin
    password: admin
    #virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

#mybaties配置
mybatis:
  mapper-locations: classpath*:/daoXml/**.xml
  check-config-location: true
  configuration:
    map-underscore-to-camel-case: true



wxconfig:
  appDi: "wx8af7c56dfab25d3c"
  appKey: "b7ab195d79b07cb00168db0484ecc1fd"
  mchDi: '1529717081'
  notifyUrl: "http://www.jiuzhijia.shop/api/notify/pay/wxPayNotifyRes.htm"
  certRootPath: ''
  spbillCreateIp: '47.111.161.18'
  refundNotifyUrl: 'http://www.jiuzhijia.shop/api/notify/pay/wxRefundNotifyRes.htm'




global:
  truePath : '/home/file/'
  nginxPath : '192.168.0.200/static/'
  defaultImg: ''
  corePoolSize: 100


logging:
  path: ./log
  level:
    com.bgd.app:  debug



