server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 800
    min-spare-threads: 30




spring:
   datasource:
      url: jdbc:mysql://192.168.0.200:3306/bgd?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      tomcat:
          max-active: 20
          initial-size: 5
          max-wait: 60000
          min-idle: 1
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: select 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


   redis:
        host: 192.168.0.200
        port: 6379

#mybaties配置
mybatis:
    mapper-locations: classpath*:/daoXml/**.xml
    check-config-location: true
    configuration:
        map-underscore-to-camel-case: true




logging:
    path: ./log
    level:
        com.bgd.admin: info


global:
  truePath : 'D:\deploy\file\'
  nginxPath : 'http://192.168.0.105:8088/static/'
  defaultImg: ''



